### PR TITLE
Js is under process

### PR DESCRIPTION
**Pull request by SarthakkKathiriya**

### CODE REVIEW

**Comment by gautamkumar1912** [comment]
https://meet.google.com/dxu-fysy-vgp

**Comment by SarthakkKathiriya** [comment]
this is the index file

**Comment by SarthakkKathiriya** [comment]
this will be batter

**Comment by gautamkumar1912** [comment]
https://meet.google.com/qqz-gycg-xsd

**Comment by SarthakkKathiriya** [comment]
https://drive.google.com/file/d/1RB7yCCd7tDW0j6KTa2Z2MlQuvjnCDcKY/view?usp=share_link

**Pull request merged**
