### PR TITLE
Day 5 fw22 0002

### PR DESCRIPTION
**Pull request by SarthakkKathiriya**

### CODE REVIEW

**Comment by gautamkumar1912** [comment]
const addToCartButton = document.querySelector('#add-to-cart-button');
addToCartButton.addEventListener('click', function(event) {
  event.preventDefault();
  const productId = 123; // replace with the actual product ID
  addToCart(productId);
});

function addToCart(productId) {
  // add the product to the cart logic goes here
}

**Comment by gautamkumar1912** [comment]
function addToCart(productId) {
  // Check if the cart exists in the browser's local storage
  let cart = JSON.parse(localStorage.getItem('cart')) || {};

  // Check if the product already exists in the cart
  if (cart[productId]) {
    // Increment the quantity of the existing item
    cart[productId].quantity++;
  } else {
    // Create a new cart item for the product
    cart[productId] = {
      name: 'Product Name', // Replace with the actual product name
      price: 9.99, // Replace with the actual product price
      quantity: 1,
    };
  }

  // Store the updated cart in local storage
  localStorage.setItem('cart', JSON.stringify(cart));
}

**Comment by SarthakkKathiriya** [comment]
https://us06web.zoom.us/j/85623396227

**Comment by gautamkumar1912** [comment]
video2886194524.mp4
<https://drive.google.com/file/d/11gj7Zq6RZdTboUPXJ2QzbBf5P9oMs2Yk/view?usp=drive_web>

**Comment by gautamkumar1912** [comment]
https://drive.google.com/file/d/11gj7Zq6RZdTboUPXJ2QzbBf5P9oMs2Yk/view?usp=sharing

**Pull request merged**
